global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['10.10.10.101:9093']

rule_files:
  - "node_down.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.10.10.101:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.10.10.101:8080']

  - job_name: 'node'
    scrape_interval: 8s
    static_configs:
      - targets: ['10.10.10.101:9100']
      - targets: ['10.10.10.102:9100']
